org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.18
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

mod_id=goldenbucket
mod_name=The Golden Bucket
mod_license=All Rights Reserved
mod_version=1.0.1
mod_group_id=dev.xzeroair.goldenbucket
mod_authors=XzeroAir
mod_website=https://github.com/XzeroAir/The-Golden-Bucket
mod_description=A Golden Bucket that stores up to three buckets of one fluid.
